### ISSUE TITLE
Could only get less than 1,000 cells detected of >= 500 transcripts

### ISSUE THREAD

**Issue by WendyZg** [ggjlab/cell_landscape#1]
Hi, hope you are doing well. 
I am processing the raw data downloaded as sra file from GSE153562 and then split into two fastq files by pfastq-dump. The preprocessing codes refer to https://github.com/ggjlab/mca_data_analysis/tree/master/preprocessing, and the follow-up analysis of DGE data refers to https://github.com/ggjlab/cell_landscape. However, I could only get less than 1,000 cells when filtering out cells with the detection of >=500 transcripts. 
I was wondering if you have any ideas to solve this problem. Please let me know if you need more information. Thank you very much.

**Comment by LifengMa** [comment]
Can you provide more detailed information? For example, which tissue(GSMXXX) do you use?

**Comment by LifengMa** [comment]
Can you provide more detailed information? For example, which tissue(GSMXXX) do you use?
